version: '3.9'
services:
  django_backend:
    container_name: django_backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    volumes:
      - django_backend:/data/db
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80

volumes:
  django_backend: {}