# Generated by Django 4.2.7 on 2023-12-26 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siteAdminModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restaurantName', models.CharField(max_length=50)),
                ('restaurantDescription', models.CharField(max_length=200)),
                ('restaurantType', models.CharField(max_length=50)),
                ('restaurantImage', models.FileField(upload_to='restaurantImage/')),
                ('restaurantLocation', models.CharField(max_length=50)),
                ('restaurantUsername', models.CharField(max_length=50)),
                ('restaurantPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenuModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=50)),
                ('foodPrice', models.IntegerField()),
                ('foodDescription', models.CharField(max_length=200)),
                ('foodImage', models.ImageField(upload_to='foodImages/')),
                ('restaurantName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.siteadminmodel')),
            ],
        ),
    ]
