# Generated by Django 4.2.3 on 2023-12-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenumodel',
            name='foodImage',
            field=models.ImageField(upload_to='foodImages/'),
        ),
        migrations.AlterField(
            model_name='siteadminmodel',
            name='restaurantImage',
            field=models.FileField(upload_to='restaurantImage/'),
        ),
    ]
