# Generated by Django 4.2.3 on 2023-12-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteadminmodel',
            name='restaurantType',
            field=models.CharField(max_length=50),
        ),
    ]
