# Generated by Django 4.2.7 on 2023-12-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmenumodel',
            old_name='foodType',
            new_name='restaurantName',
        ),
    ]
