# Generated by Django 4.2.3 on 2023-12-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_restaurantmenumodel_foodimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteadminmodel',
            name='restaurantImage',
            field=models.FileField(upload_to='../../../Frontend/src/backendImages/media/'),
        ),
    ]
