# Generated by Django 4.2.3 on 2023-12-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_siteadminmodel_restauranttype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantAdminProfileModel',
            new_name='RestaurantUpdateInfoModel',
        ),
    ]
