# Generated by Django 4.2.3 on 2023-12-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_siteadminmodel_restaurantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteadminmodel',
            name='restaurantImage',
            field=models.FileField(upload_to='restaurantImage/'),
        ),
    ]
