# Generated by Django 4.2.7 on 2023-11-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
